In [127]:
import pickle
import numpy as np
from constants import Map
from  numpy.linalg import lstsq

In [99]:
kill_matrix = pickle.load(open('kill_matrix_by_map.pkl', 'rb'))
day_kill_mat = kill_matrix[Map.map_day]
night_kill_mat = kill_matrix[Map.map_night]
dusk_kill_mat = kill_matrix[Map.map_dusk]


In [16]:
def kill_prob_mat(kill_count_mat):
    return kill_count_mat / (kill_count_mat + kill_count_mat.T)

In [86]:
kill_prob_mat(day_kill_mat)

array([[0.5       , 0.61065294, 0.72674799],
       [0.38934706, 0.5       , 0.65897133],
       [0.27325201, 0.34102867, 0.5       ]])

In [100]:
kill_prob_mat(night_kill_mat)

array([[0.5       , 0.63015529, 0.74482759],
       [0.36984471, 0.5       , 0.64261812],
       [0.25517241, 0.35738188, 0.5       ]])

In [105]:
kill_prob_mat(dusk_kill_mat)

array([[0.5       , 0.57899414, 0.71772674],
       [0.42100586, 0.5       , 0.65665302],
       [0.28227326, 0.34334698, 0.5       ]])

In [113]:
day_kill_mat

array([[83565, 26804, 55525],
       [17090, 12416, 22293],
       [20877, 11537, 27320]], dtype=int32)

In [123]:
def make_values_mat(count_mat):
    values_mat = np.zeros((4,3), float)
    values_mat[0, 0] = 1
    values_mat[0, 1] = -count_mat[0, 1] / count_mat[1, 0]
    values_mat[1, 0] = 1
    values_mat[1, 2] = -count_mat[0, 2] / count_mat[2, 0]
    values_mat[2, 1] = 1
    values_mat[2, 2] = -count_mat[1,2] / count_mat[2,1]
    values_mat[3, 2] = 1
    return values_mat

In [135]:
def solve_values(count_mat):
    values = lstsq(make_values_mat(count_mat), [0, 0, 0, 1], rcond=None)[0]
    return values / values[2]

print('day  ', solve_values(day_kill_mat))
print('night', solve_values(night_kill_mat))
print('dusk ', solve_values(dusk_kill_mat))


day   [2.74281282 1.80183344 1.        ]
night [2.94845105 1.74780938 1.        ]
dusk  [2.56516077 1.88156994 1.        ]
